import { StyleSheet } from "react-native";

export default StyleSheet.create(
    {
        container:{
            flex:1,
            backgroundColor:"#fce4c6"
        },
        /* Header */
        header:{
          flexDirection:'row',
          justifyContent:'center',
          backgroundColor:'white',
          borderBottomRightRadius:40,
          borderBottomLeftRadius:40,
          marginBottom:5,
          height:'7%'
        },
        /* Main */
        main:{
          flex:1,
          margin:0,
          overflow:"scroll",
          backgroundColor:"#fce4c6",
          height:"93.5%",
          width:"100%",
        },
        ScrollBar:{
          padding:6,
        },
        book:{
          padding:0,
          marginTop:22.5,
          minHeight:128,
        },
        book_touchable:{
          flexDirection:'row',
          justifyContent:'space-between',
          alignItems:'flex-start'
        },
        book_logo:{
          width:120,
          height:120,
          marginLeft:10,
          marginTop:-20
        },
        book_content: {
          marginRight:30
        },
        book_title:{
          fontFamily:"Black",
          fontSize:16,
          color:'white',
          marginTop:15,
          marginBottom:12
        },
        book_about:{
          fontFamily:"Medium",
          fontSize:12,
          color:'#fafff4',
          marginRight:15
        },
        /* Form History */
        forms:{
          height:'90%',
          margin:4,
          backgroundColor:'transparent',
          borderRadius:8,
          padding:14
        },
        forms_main: {
          backgroundColor:'white',
          borderRadius:8,
          padding:14,
          height:"93.5%"
        },
        form_row: {
          backgroundColor:'#f1f1f1a8',
          borderRadius:8,
          padding:11,
          flexDirection:'row',
          justifyContent:'flex-end',
          alignItems:'center',
          marginTop:12
        },
        form_row_title: {
          textAlign:'right',
          fontFamily:'Medium',
          fontSize:15,
          paddingRight:8,
          color:'#000000b8'
        },
        /* Writers */
        writers:{
          height:'90%',
          margin:4,
          backgroundColor:'transparent',
          borderRadius:8,
          padding:4
        },
        writers_row: {
          backgroundColor:'transparent',
          borderRadius:8,
          padding:14,
          flexDirection:'column',
          justifyContent:'space-between',
          height:180,
          marginBottom:14
        },
        /* About */
        about:{
          height:'90%',
          backgroundColor:'transparent',
          borderRadius:8,
          padding:14,
          margin:4
        },
        about_detial: {
          backgroundColor:'white',
          borderRadius:8,
          padding:14
        },
        about_detial_text:{
          textAlign:'center',
          fontSize:14,
          fontFamily:'Medium'
        },
        about_builders:{
          flexDirection:'row',
          justifyContent:'center',
          alignItems:'center',
          marginTop:12.5,
          paddingTop:15
        },
        about_builders_section_right:{
          marginRight:15,
          backgroundColor:'white',
          borderRadius:8,
          padding:14,
          alignItems:'center',
          width:'45%'
        },
        about_builders_section_left:{
          marginLeft:15,
          backgroundColor:'white',
          borderRadius:8,
          padding:14,
          alignItems:'center',
          width:'45%'
        },
        about_builders_section_title:{
          textAlign:'center',
          fontSize:14,
          fontFamily:'Black',
          marginTop:10
        },
        about_builders_section_detial:{
          textAlign:'center',
          fontSize:14,
          fontFamily:'Medium',
          marginTop:5
        },
        /* Bottom Main Menu */
        menu:{
            margin:0,
            padding:0,
            overflow:"hidden",
            backgroundColor:"#ffffff",
            position:"absolute",
            bottom:0,
            width:"100%",
            flexDirection:"row",
            justifyContent:"flex-end",
            borderTopRightRadius:40,
            borderTopLeftRadius:40,
        },
        menu_item:{
            backgroundColor:"#ffffff",
            padding:8,
            width:"25%",
            flexDirection:"row",
            justifyContent:"center",
            borderColor:"#e6ebe054",
            borderLeftWidth:0.45,
            borderRightWidth:0.45,
            borderTopColor:"#d5dbce",
            borderTopWidth:0.45
        },
        menu_item_image:{
            width:30,
            height:30
        }
    }
)